### ISSUE TITLE
Fix NullPointerException on contacts filtering

### ISSUE THREAD

**Issue by HenriDellal** [HenriDellal/emerald-dialer#1]
As can be seen from the GP logs, the application crashes on T9 search. See ContactsEntryAdapter, lines 269, 103. The regexQueryResults field is null in getCount even though the filter submits results to it before the notifyDataSetChanged method is called. Sadly I can't reproduce it, so if someone has encountered this bug, please tell me when exactly it happens and under which conditions.

**Comment by fdelapena** [comment]
Hi, thanks for the app.

I'm not sure of the same bug, but I am able to reproduce it here always: 

Tap on Voice Mail in speed dial crashes. That is probably because the Voice Mail number is unset in my case.

Tested with 1.0.1 on LG with Android 6.0.1.

**Comment by HenriDellal** [comment]
Hello.
Thank you for mentioning another bug. It's not related to this one, but very helpful still. It appears that the app needs another permission to read/write voice mail settings.
