### ISSUE TITLE
Could T9 support Chinese?

### ISSUE THREAD

**Issue by ivysrono** [HenriDellal/emerald-dialer#12]
There are 3 support Chinese:
[MoKee/android_packages_apps_Dialer](https://github.com/MoKee/android_packages_apps_Dialer)

[DW](https://play.google.com/store/apps/details?id=com.dw.contacts.free)

[Ex](https://play.google.com/store/apps/details?id=com.modoohut.dialer)

**Comment by HenriDellal** [comment]
Hello.
Thank you for providing the links, it's very helpful. I believe that it's possible, but it may require a lot of changes in the code.

**Comment by schapira** [comment]
hi, please add another keyboards available for T9, like Arabic, Hebrew etc.

**Comment by HenriDellal** [comment]
Hello, @schapira. I hope to do it for as much languages as possible, including the ones you've mentioned.

**Comment by schapira** [comment]
hi, any news on this? I wait for it to replace old "dailer one" app, till then I cannot use emerald.

**Comment by HenriDellal** [comment]
Hello.
I don't have a lot of free time these days, so I'm unable to provide this update soon.

**Comment by sprnza** [comment]
Thanks for the project! Could we have Russian language, please?

**Comment by HenriDellal** [comment]
Здравствуйте.
В программе есть поиск Т9 на русском языке, но он может быть недоступен, если системным выбран другой язык. Эта проблема может быть решена добавлением пункта выбора языка в настройках.

**Comment by sprnza** [comment]
Да, у меня системный язык выбран английский и русского Т9, к сожалению, нет. Возможность выбора в настройках была бы весьма кстати! :)

**Comment by schapira** [comment]
Is something simple? can you guide me how to add it and I will do the work?

**Comment by HenriDellal** [comment]
The easiest way is to submit the keys and corresponding symbols, like
```
2 - ABCabc
```

**Comment by schapira** [comment]
2- דהו
3-אבג
4-מםנן
5-יכךל
6-זחט
7-רשת
8-צץק
9-סעפף

**Comment by schapira** [comment]
hi, thanks for adding the Hebrew keymap. today I finally show it on the last release. but it seems that the search doesn't work.

**Comment by ivysrono** [comment]
[oasisfeng/android-smartdial-chinese: Xposed moduel to provide smart dialing with T9 Pinyin in AOSP dialer app](https://github.com/oasisfeng/android-smartdial-chinese)

**Comment by ivysrono** [comment]
@HenriDellal Does this app still maintained?

**Comment by HenriDellal** [comment]
@ivysrono I've abandoned all android projects for a while, don't know if I'll return to them

**Comment by schapira** [comment]
sorry to hear that.
but this issue shouldn't be close

**Comment by ivysrono** [comment]
@HenriDellal return?

**Comment by HenriDellal** [comment]
Done, will be available in 1.0.10
