### ISSUE TITLE
Select Contact to call

### ISSUE THREAD

**Issue by shawn1thompson** [HenriDellal/emerald-dialer#24]
Is there a way to select a contact to call? I'm suspecting it might be the plus sign, but when I tap that it says there is no contacts application installed to save contacts. I'm using Simple Contacts on F-Droid as my contacts app. Thanks for this though. I've been looking for a replacement for Google's phone app.

**Comment by HenriDellal** [comment]
Hello.
Thanks for the feedback. Seems like there is a way to fix it, so I'll look into it soon.
