### ISSUE TITLE
App Crash on Android8.1 with logcat

### ISSUE THREAD

**Issue by qqzwc** [HenriDellal/emerald-dialer#25]
11-16 13:38:42.588 10700 11114 W Filter  : An exception occured during performFiltering()!
11-16 13:38:42.588 10700 11114 W Filter  : java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
11-16 13:38:42.588 10700 11114 W Filter  : 	at java.util.regex.Matcher.reset(Matcher.java:1052)
11-16 13:38:42.588 10700 11114 W Filter  : 	at java.util.regex.Matcher.<init>(Matcher.java:180)
11-16 13:38:42.588 10700 11114 W Filter  : 	at java.util.regex.Pattern.matcher(Pattern.java:1006)
11-16 13:38:42.588 10700 11114 W Filter  : 	at ru.henridellal.dialer.ContactsEntryAdapter$ContactsFilter.filterWithRegex(ContactsEntryAdapter.java:270)
11-16 13:38:42.588 10700 11114 W Filter  : 	at ru.henridellal.dialer.ContactsEntryAdapter$ContactsFilter.performFiltering(ContactsEntryAdapter.java:302)
11-16 13:38:42.588 10700 11114 W Filter  : 	at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
11-16 13:38:42.588 10700 11114 W Filter  : 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-16 13:38:42.588 10700 11114 W Filter  : 	at android.os.Looper.loop(Looper.java:164)
11-16 13:38:42.588 10700 11114 W Filter  : 	at android.os.HandlerThread.run(HandlerThread.java:65)
11-16 13:38:42.596 10700 10700 D AndroidRuntime: Shutting down VM
11-16 13:38:42.596 10700 10700 E AndroidRuntime: FATAL EXCEPTION: main
11-16 13:38:42.596 10700 10700 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 10700
11-16 13:38:42.596 10700 10700 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at ru.henridellal.dialer.ContactsEntryAdapter.getCount(ContactsEntryAdapter.java:105)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:836)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6407)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:52)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at ru.henridellal.dialer.ContactsEntryAdapter$ContactsFilter.publishResults(ContactsEntryAdapter.java:313)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-16 13:38:42.596 10700 10700 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
11-16 13:38:42.601  1333 11338 W ActivityManager:   Force finishing activity ru.henridellal.dialer/.DialerActivity
11-16 13:38:42.607  1333  1522 I ActivityManager: Showing crash dialog for package ru.henridellal.dialer u0

11-16 00:25:56.182 30619 16088 F google-breakpad: -----BEGIN BREAKPAD MICRODUMP-----
11-16 00:25:56.182 30619 16088 F google-breakpad: V UNKNOWN:0.0.0.0
11-16 00:25:56.183 30619 16088 F google-breakpad: O A arm 04 armv8l 3.18.124-BlackScreen-5.4 #3 SMP PREEMPT Mon Nov 5 19:06:22 EST 2018
11-16 00:25:56.183 30619 16088 F google-breakpad: P UNKNOWN
11-16 00:25:56.183 30619 16088 F google-breakpad: G UNKNOWN
11-16 00:25:56.192 30619 16088 F google-breakpad: H 12C00000 FFFF1000 01A5 33BB0000 60ADD000 0C:70 0D:50 0E:2B 0F:24 10:28 11:21 12:24 13:18 14:08 15:02 16:03 17:01 1B:01 1C:01 1D:01
11-16 00:25:56.192 30619 16088 F google-breakpad: -----starting crashing thread-----
11-16 00:25:57.040 16083 16088 F libc    : Fatal signal 11 (SIGSEGV), code 239474504, fault addr 0x447846 in tid 16088 (Jit thread pool), pid 16083 (ngdong.app.mall)
11-16 00:25:57.145 16083 16088 F libc    : failed to resend signal during crash: Invalid argument

**Comment by HenriDellal** [comment]
Thank you! This log is very helpful, I'll work on it.

**Comment by HenriDellal** [comment]
Please could you try this fix? If you've installed the dialer from F-Droid, you have to uninstall the dialer first.

[dialer.zip](https://github.com/HenriDellal/emerald-dialer/files/2588603/dialer.zip)

**Comment by HenriDellal** [comment]
I think I wrote the fix, but I'm a bit puzzled.
[dialer.zip](https://github.com/HenriDellal/emerald-dialer/files/2589071/dialer.zip)

**Comment by qqzwc** [comment]
Tested and confirmed. There is no crash now. Thanks for your hard work~

**Comment by HenriDellal** [comment]
It could be harder without your help, thank you very much.
