### ISSUE TITLE
a really black theme

### ISSUE THREAD

**Issue by DJCrashdummy** [HenriDellal/emerald-dialer#31]
beforehand: thank you very much for this awesome app!!! :clap: 

i would love to ditch the long time ago abandoned [_Dialer2_](https://f-droid.org/packages/org.dnaq.dialer2/) in favour of _Emerald Dialer_, but one thing i sorely miss is a black theme (not just a dark one - which IMHO hardly makes sense).
especially for AMOLED-displays it is a big difference and huge improvement!

**Comment by HenriDellal** [comment]
Hello.
Thanks for the feedback. Seems like it should be easy to implement.

**Comment by HenriDellal** [comment]
Will be available in the next release
