### ISSUE TITLE
T9 filtering not working with accented/diacritic characters

### ISSUE THREAD

**Issue by sibidi** [HenriDellal/emerald-dialer#33]
Hello Henri. I'm French and as such some of my contacts have accents in their names, e.g. Stéphane. These names don't show up in the T9 filtering.
Typing 78 will show Stéphane along with Quentin, Puffy and Purcell, but 783 will only show Quentin and Puffy, not Stéphane.
Do you think fixing this would be complicated?
It works properly with my stock dialer.
Thanks.

Benjamin

**Comment by HenriDellal** [comment]
Hello.
It should be easy if I know what letters are under what numbers.

**Comment by sibidi** [comment]
Here's the list for French:
à â ä À Â Ä = a
é è ê ë É È Ê Ë = e
ï î Î Ï = i
ô ö Ô Ö = o
ù û ü Ù Û Ü = u
ÿ  Ÿ = y
ç Ç = c

I know there's many more for other languages, like ñ in Spanish.

Thanks,

Benjamin

**Comment by sonbua** [comment]
Hi Henri, could you please add this list for Vietnamese
à á ả ã ạ À Á Ả Ã Ạ ă ằ ắ ẳ ẵ ặ Ă Ằ Ắ Ẳ Ẵ Ặ â ầ ấ ẩ ẫ ậ Â Ầ Ấ Ẩ Ẫ Ậ = a = keypad 2
è é ẻ ẽ ẹ È É Ẻ Ẽ Ẹ ê ề ế ể ễ ệ Ê Ề Ế Ể Ễ Ệ = e = keypad 3
ì í ỉ ĩ ị Ì Í Ỉ Ĩ Ị = i = keypad 4
ò ó ỏ õ ọ Ò Ó Ỏ Õ Ọ ô ồ ố ổ ỗ ộ Ô Ồ Ố Ổ Ỗ Ộ ơ ờ ớ ở ỡ ợ Ơ Ờ Ớ Ở Ỡ Ợ = o = keypad 6
ù ú ủ ũ ụ Ù Ú Ủ Ũ Ụ ư ừ ứ ử ữ ự = u = keypad 8
ỳ ý ỷ ỹ ỵ Ỳ Ý Ỷ Ỹ Ỵ = y = keypad 9

Many thanks,
/Son
