### ISSUE TITLE
Date format of LogEntry to restrictive 

### ISSUE THREAD

**Issue by marscher** [HenriDellal/emerald-dialer#36]
It would be nice to see the call time even for previous days. Currently the call time is simply omitted, if the call has happened the day before today. Maybe we could add an option for this? Like users can input a string format code for the entries. I can submit a PR for this if desired.

**Comment by HenriDellal** [comment]
Hello.
Thanks for the feedback. I think that it can be done in a different way as well. I'd like to show additional call information in the dialog window, where the extended time format can be used. Please could you share your opinion about it?

**Comment by marscher** [comment]
Hi Henri,
I do not understand which dialog you are referring to (version 1.0.5). Are you saying, that you want to add such an extended dialog window to get the details of a call (e.g. duration, exact time etc.)?

**Comment by HenriDellal** [comment]
Yes. It should appear when the log entry is long pressed.
