### ISSUE TITLE
[SOLVED] Crash when tapping button on dialer.

### ISSUE THREAD

**Issue by NitroNils** [HenriDellal/emerald-dialer#4]
App chrashes when tapping a button on the dialer.
All else seems perfectly fine.
All permissions granted.

A bugreport has been generated by the OS - just need an email.address tobsend it to.

_Android version 6.0
Huawei p8 Lite (ALE-L21)
EMUI 4.0.3_ 

More details in report. 

EDIT:
 _App version: 1.02_

**Comment by HenriDellal** [comment]
Please could you send the bug report to anridellal@gmail.com?

**Comment by HenriDellal** [comment]
As it appears from the report given, the reason of such behaviour is number being null value. I was trying to find the roots of it, but haven't yet.

**Comment by davidmattson1** [comment]
Same issue here Pixel XL

**Comment by NitroNils** [comment]
Same issue on
_App version: 1.03_

**Comment by Thespartann** [comment]
For me 1.03 crashes instantly now. Before it crashed when tapping a button. Now always crashes.
Good luck with it. I hope this is going somewhere.

**Comment by fdelapena** [comment]
> As it appears from the report given, the reason of such behaviour is number being null value. I was trying to find the roots of it, but haven't yet.

Did you try unsetting the Voice mail number from the SIM configuration? This one is the only case always crashing to me possibly due to this reason.

**Comment by fdelapena** [comment]
It always crashes to me when I touch in the recent calls in the list but only in the avatar, not in the number. I don't have those numbers as contacts (in fact, I don't have contacts at all).

**Comment by FrancoisMz** [comment]
Hello,
For your information, release 1.0.5 fixed this issue for me on the following devices:
Samsung S6 Android 7.0
BQ Aquaris M5 Android 7.1.2
BQ Aquaris V Android 7.1.2
Previously, it was systematically crashing when tapping a phone number (and perhaps sometimes when tapping in the recent calls).

**Comment by NitroNils** [comment]
Yes, Fixed in later versions!
