### ISSUE TITLE
Calling screen ?

### ISSUE THREAD

**Issue by joeyLaus** [HenriDellal/emerald-dialer#40]
Im looking for a way to completely replace the stock app in LineageOS called "Phone" or the stock "Dialer"

Emerald Dialer works in a way to only dial the number, however after dialing the number, the "calling screen" that appears comes from the stock app, so Emerald Dialer does not have its own calling screen.  Can this be implemented?

**Comment by daniele-athome** [comment]
I believe a partial response can be found in #19.
