### ISSUE TITLE
Saved Numbers Can't be seen in History Just Numbers 

### ISSUE THREAD

**Issue by methuselahin** [HenriDellal/emerald-dialer#42]
I am using NUBIA RedMagic 8.1 stock ROM. The stock  dialer shows all the numbers when i get or dials any calls.I am talking about saved names in the phonebook. But the Emerald dialer doesn't show anything. Issue had been reported earlier also. But if i can grab somehow any log tell me what logcat you want! maybe i can help. 
![to be uploaded](https://user-images.githubusercontent.com/10970138/56259661-70f4ff80-60f1-11e9-9c91-4ec01878514c.png)

**Comment by sachoosaini** [comment]
@HenriDellal do you even the bugs bro? Do you need logcat? waiting for reply

**Comment by HenriDellal** [comment]
Hello.
Sorry for the long reply, I'm very busy these days and forget to answer. I'd like to get a logcat, but I should modify the apk first probably to make it more verbose. Anyway, if you can get the logs, please use these instructions: https://gsantner.net/android-contribution-guide/?packageid=ru.henridellal.emerald&name=Emerald%20Dialer&web=https://github.com/HenriDellal/emerald
Then remove any sensitive data from logs (phone numbers, etc) and share it via e-mail (anridellal at gmail) or here.

**Comment by sachoosaini** [comment]
what about Sending reply log via matlog? @HenriDellal

**Comment by sachoosaini** [comment]
what about sending log via metlog? @HenriDellal

**Comment by eandersons** [comment]
I have the same problem. Contact image is shown in the call log but not the name.
Emerald Dialer currently is not the default phone app as the current contacts application requires to be the default app in order to make calls.
I have seen Emerald Dialer working correctly for a short period of time but I cannot recall the circumstances.
