### ISSUE TITLE
Emerald Dialer V1.0.7 - Re-opening the app after rejecting permission request Crashes the app.

### ISSUE THREAD

**Issue by realrufans** [HenriDellal/emerald-dialer#47]
#### Expected behavior

I expect it to request for permission again after it was rejected the first time. 

#### Actual behavior

Re-opening the app after rejecting permission request Crashes the app. 

#### How to reproduce

* Install the app, and launch it
* Reject the permission request
* Reopen the app
* Watch it crash

##### Browser/App version:
Emerald Dialer V1.0.7 -

##### Operating system:
Android 0

#### Recording Of The Bug

![MNML-May26-0618-1558891280628.gif](https://cdn.steemitimages.com/DQmXjwaE5U42difSQxnKe1ojCKVxZnxqmZrpU2iTE8bbCiC/MNML-May26-0618-1558891280628.gif)

**Comment by HenriDellal** [comment]
Hello.
I've managed to reproduce the bug, though I was able to get permissions request popup again. I plan to fix it soon.
Thank you.
