### ISSUE TITLE
Too broad dialer

### ISSUE THREAD

**Issue by methuselahin** [HenriDellal/emerald-dialer#48]
Well my screen is 6inch, my hand is not that big. So to reach the * i need to hold my phone from another side.
![Screenshot_2019-05-28_08-20-39](https://user-images.githubusercontent.com/10970138/58447310-a1cd4900-8121-11e9-9354-59f80b8a63a0.png)
my phone has aosp stock ROM. And this is almost aosp dialer, see the difference. 
![Screenshot_2019-05-28_08-23-34](https://user-images.githubusercontent.com/10970138/58447453-0f797500-8122-11e9-9101-a50473a97066.png)

**Comment by HenriDellal** [comment]
Thanks for the feedback. It should be rather easy to fix.

**Comment by methuselahin** [comment]
@henridellal I know for you it will be easy. But with small hands and these big screens it really getting difficult to use phones. Day by day screens and getting bigger and better but lol..hands gonna stay same

**Comment by HenriDellal** [comment]
I did a small change to add side gaps for numpad on wide screens. The new version is available on Releases section, it will appear on F-Droid soon.

**Comment by methuselahin** [comment]
> I did a small change to add side gaps for numpad on wide screens. The new version is available on Releases section, it will appear on F-Droid soon.

well thats great. Lets see how it goes. Will report back.

**Comment by FliegendeWurst** [comment]
Instead of two gaps on each side, one bigger gap on the left or right side could function as a 'one-hand-mode'.
