### ISSUE TITLE
Place calls from the speed dial page.

### ISSUE THREAD

**Issue by cckole** [HenriDellal/emerald-dialer#49]
The `speed dial` to me should be like a short cut to dialling some added numbers, but it seems the functions i've seen it perform is not close to that. I can only add numbers or pick contact numbers. Wouldnt it be nice if calls can be place from the speed dials page. At least that would make calling the added numbers easy and faster. It would also act as a page for favourite contacts, so automatically, the frequently dialled numbers would be the numbers that most users will add to the speed dial page. That would be a nice approach. What do you think?

**Comment by HenriDellal** [comment]
Thank you for the idea, I like it, though I don't know what's the best way to start a call.

**Comment by cckole** [comment]
### Let me give you a hint on how to go about it with the mock ups below.

**The current behaviour of the speed dial feature**: If you long press any number added to the speed dial page, a pop up will show asking whether you want to remove the number. This behaviour will change if you want to implement the call feature. Once any number is long pressed, there will be a pop up Just like the image below.

![gfhfg](https://user-images.githubusercontent.com/36272218/58702749-9044a500-839e-11e9-8e74-682c5d557691.png)

From the above image, you can see that there are two options. `Remove number` and `Call`. When you click on `remove number`, it will pop up the page where you can remove the number. You can see that it later boils down to the first feature you see when you long press any number. 
Moreso, pressing the `call` will pop up the image below.

![hgdhueu](https://user-images.githubusercontent.com/36272218/58703109-81122700-839f-11e9-9506-2937e9636efa.png)

Through this method, placing call from the speed dial page will be easy.

**Comment by HenriDellal** [comment]
Done, thanks for help.

**Comment by cckole** [comment]
You are welcome
