### ISSUE TITLE
Voice Mail option is not working

### ISSUE THREAD

**Issue by friendsmobile** [HenriDellal/emerald-dialer#50]
# Project Information

* Repository: https://github.com/HenriDellal/emerald-dialer
* Project Name:  emerald-dialer
* My Github Account: https://github.com/friendsmobile

# Expected behavior

When I click the Voice Mail option, then a list of numbers should be displayed from where I can choose the custom Voice Mail number

# Actual behavior
When I click the Voice Mail option, no options appear

# How to reproduce

* [Download ](https://github.com/HenriDellal/emerald-dialer/releases)the app 
* Click the bottom 3 horizontal lines at the bottom right
* click on the Speed Dail
* click on Voice Mail
* Note the BUG

* Browser/App version: v1.0.8
* Operating system: 6.0

# Recording Of The Bug

![20190601_032635](https://user-images.githubusercontent.com/51118734/58738036-eb839100-83b8-11e9-9eaf-9b94b85d1a10.gif)

**Comment by HenriDellal** [comment]
It won't work if your phone doesn't have voice mail settings activity specified by system, so it's not a dialer bug.
