### ISSUE TITLE
Add biometric login and Import Contacts from Excel

### ISSUE THREAD

**Issue by shadutopian** [HenriDellal/emerald-dialer#53]
The first feature that I want to suggest is Biometric Login . Biometric login means using your finger print or iris scanner or face scanner. It is simply related to person's body which can be used to unlock a phone or application. This feature will add more security to the application and no one will be able to access the application without the permission.
The second feature that I want to suggest is Important Contacts from Excel. Sometimes the users save their contacts on a spreadsheet or excel sheet and if they change a device, they can simply import the contacts from that excel. They just have to choose the path and upload the contacts.

**Comment by HenriDellal** [comment]
The first feature should be implemented with system-wide application. The second feature is not related to dialer's functionality.
