### ISSUE TITLE
Greek T9

### ISSUE THREAD

**Issue by tdafos** [HenriDellal/emerald-dialer#68]
I would like to try to add the T9 keyboard for the greek language. Can you tell me which files should I change in order to do so?
I have some experience in writing android apps I am just not sure where I should add the data.

**Comment by HenriDellal** [comment]
First step is to copy `app/src/main/res/values/strings.xml` to `app/src/main/res/values-el/strings.xml`. In this file you have to change string values for ids:
- `numpad_2` to `numpad_9` to change keyboard appearance. These are usually capitalized letters.
- `regex_2` to `regex_9`. These strings contain regexes used by search and usually are in form of number, uppercase and lowercase letters in square brackets

Example:
```
	<string name="numpad_2">ABC</string>
	<string name="regex_2">[2ABCabc]</string>
```

**Comment by tdafos** [comment]
Perfect, it's simple enough. I will get right to it.

**Comment by HenriDellal** [comment]
Thanks, I've saved and checked it, will add soon.
