### ISSUE TITLE
feature request: Chinese number format

### ISSUE THREAD

**Issue by ivysrono** [HenriDellal/emerald-dialer#70]
Chinese dialer number: `123-4567-8901`, or `12345678901`, or `+86-xxx`
US format is so strange for Chinese: `1 123-456-7890`

Maybe add option to hide  `-` is the most simple way.

**Comment by HenriDellal** [comment]
Seems like you have English locale as system, this issue can be fixed if t9 locale is taken into account for formatting.

**Comment by ivysrono** [comment]
Ok, I will wait F-Droid push 1.0.10.
