### ISSUE TITLE
feature request: show contacts' name on call log

### ISSUE THREAD

**Issue by ivysrono** [HenriDellal/emerald-dialer#71]
1.0.10 only show call log number without name.

**Comment by HenriDellal** [comment]
Please could you tell if you have same problem when you type a number (not in call log)?

**Comment by ivysrono** [comment]
No, name will show after I type any number.

**Comment by ivysrono** [comment]
1.0.13 still

**Comment by ivysrono** [comment]
The calls before emerald installed have this bug.
It's not important.
