### ISSUE TITLE
[Bug] Settings are dark on light theme

### ISSUE THREAD

**Issue by AlexanderRitter02** [HenriDellal/emerald-dialer#73]
### What happens
Even though **light** theme is enabled, the _settings_ screen appears in a **dark** color, making it nearly unreadable in a sunny place.
The main app screen is displayed properly in light mode.
My system theme is also on light, so it's not that.

See picture: <img src="https://user-images.githubusercontent.com/42546705/129437922-9d762e5e-f251-46b1-b10d-12e4b57699c2.jpg" height=400> </img>

### Device Info
- Android 10
- Emerald Dialer 1.0.11 (latest atm)

**Comment by HenriDellal** [comment]
Fixed, will be available in new release.
