### ISSUE TITLE
Contact name not showing when receiving calls

### ISSUE THREAD

**Issue by Septherion** [HenriDellal/emerald-dialer#76]
Hey guys, love the app, but the only issue I have is when I receive calls, only the callers number shows, and not his name, even if it figures in my contact book. Have a clue? Thank you!

**Comment by HenriDellal** [comment]
Hello,

Thank you for the feedback. Do you mean that the contact name is missing in the dialer's log? If so, do you notice same issue in other dialers? (e.g. stock dialer, Simple Dialer, etc)

**Comment by Septherion** [comment]
The contact name appears in the log, but not when they call me. When I receive the call I only have the number.

Names do appear when I'm using stock app or Simple Dialer for instance. I have other issues with those apps though, this being the reason why I use emerald dialer.

**Comment by HenriDellal** [comment]
Emerald Dialer doesn't include in-call UI, so this issue is related to your default phone application.
