### ISSUE TITLE
Feature Request: Multilanguage T9 search

### ISSUE THREAD

**Issue by WallK** [HenriDellal/emerald-dialer#80]
I'd like to have multilanguage T9 search (not one language at a time, but multiple)
For example, 2562 should match "blob" in English and "гора" in Ukrainian
My Xiaomi phone dialer does that and I'm very used to it
Thanks!

**Comment by WallK** [comment]
Thank you, works like a charm!

**Comment by bb1a2** [comment]
@HenriDellal Let me know if you want me to create a separate issue for https://github.com/HenriDellal/emerald-dialer/issues/80#issuecomment-1899288159

**Comment by HenriDellal** [comment]
@bb1a2 it is implemented now, will be available in the next release. By the way, it is recommended to create new issues if the suggestion is not related to discussion.

**Comment by bb1a2** [comment]
Thanks
